name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Install GO
       uses: actions/setup-go@v2
       with:
         go-version: 1.18

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Fetch modules for GO
       run:  go mod download

     - name: Build
       run: go build -v ./...

     - name: Run test
       run: go test -v ./...
    
     - name: Docker build
       run: docker build -t dkasymov/go_sample .
     
     - name: Docker miltistage
       run: docker build -t dkasymov/go_sample -f Dockerfile.multistage .
       
          