name: CD

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input tags'
        required: true
        type: string
      skip-test:
        description: 'Skip test'
        required: true
        type: boolean
      skip-build:
        description: 'Skip build'
        required: true
        type: boolean

jobs:
  test:
    if: ${{ github.event.inputs.skip-test }} == true
    runs-on: ubuntu-latest
    steps:
      - name: Test Go
        run: go test -v ./...
  build:
    if: ${{ github.event.inputs.skip-build }} == true
    runs-on: ubuntu-latest
    steps:
      - name: Build Go
        run: go build -v ./...
  publish:
   runs-on: ubuntu-latest
   steps:
     - name: Install GO
       uses: actions/setup-go@v2
       with:
         go-version: 1.18 

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Fetch modules for GO
       run:  go mod download

     - name: Build
       run: go build -v ./...

     - name: Run test
       run: go test -v ./...
    
     - name: Docker build
       run: docker build -t dkasymov/go_sample .
       
     - name: Docker miltistage
       run: docker build -t dkasymov/go_sample -f Dockerfile.multistage .