name: CD

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Input tags'
        required: true
        type: string
      skip-test:
        description: 'Skip test'
        required: true
        type: boolean
      skip-build:
        description: 'Skip build'
        required: true
        type: boolean

jobs:
  publish:
   runs-on: ubuntu-latest
   steps:
     - name: Install GO
       uses: actions/setup-go@v2
       with:
         go-version: 1.18 

     - name: Checkout code
       uses: actions/checkout@v3

     - name: Fetch modules for GO
       run:  go mod download

     - name: Build
       run: go build -v ./...

     - name: Run test
       run: go test -v ./...
     
     - name: Login to DockerHub
       uses: docker/login-action@v2
       with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
     - name: Build and Push
       uses: docker/build-push-action@v3
       with:
          push: true
          context: .
          tags: dkasymov/go_sample:${{ github.event.inputs.tag }}